/* Fallback player names for Quiz Ball suggestions and answer matching. */
window.QUIZ_PLAYER_NAMES = [
    "Achille Polonara", "Adam Atamna", "Adam Hanga",
    "Admiral Schofield", "Alberto Abalde", "Alec Peters",
    "Aleksa Avramovic", "Aleksander Balcerowski", "Aleksej Nedeljkovic",
    "Aleksej Pokusevski", "Alen Smailagic", "Alessandro Pajola",
    "Alex Abrines", "Alex Poythress", "Alexandros Samodurov",
    "Aliou Diarra", "Allan Dokossi", "Alpha Diallo",
    "Alpha Kaba", "Amath M'Baye", "Andreas Obst",
    "Andrejs Grazulis", "Andres Feliz", "Ante Zizic",
    "Antonio Blakeney", "Antonius Cleveland", "Arijan Lakic",
    "Armando Bacot Jr.", "Armel Traore", "Armoni Brooks",
    "Arnas Butkevicius", "Arturs Zagars", "Awudu Abass",
    "Azuolas Tubelis", "Balsa Koprivica", "Bandja Sy",
    "Bar Timor", "Bastien Vautier", "Boban Marjanovic",
    "Bodian Massa", "Bonzie Colson", "Boris Dallo",
    "Boubacar Toure", "Brady Manek", "Brandon Boston Jr.",
    "Brandon Davies", "Brandon Taylor", "Branko Lazic",
    "Bruno Fernando", "Bryant Dunston", "Carlik Jones",
    "Carsen Edwards", "Cedi Osman", "Charles Kahudi",
    "Chima Moneke", "Chimezie Metu", "Chris Jones",
    "Chuma Okeke", "Clement Frisch", "Cleveland Antonius",
    "Codi Miller-Mcintyre", "Cole Swider", "Collin Malcolm",
    "Dalibor Ilic", "Damien Inglis", "Dan Oturu",
    "Daniel Diez", "Daniel Hackett", "Daniel Theis",
    "Danielius Lavrinovicius", "Danilo Andjusic", "Danko Brankovic",
    "Dario Brizuela", "Darius Thompson", "Daulton Hommes",
    "David Kraemer", "David Kramer", "David Lighty",
    "David Mc Cormack", "David Mccormack", "Davis Bertans",
    "Deividas Sirvydis", "Dejan Davidovac", "Derek Willis",
    "Derrick Alston Jr.", "Devin Booker", "Devon Hall",
    "Devontae Cacok", "Diego Flaccadori", "Dimitris Moraitis",
    "Dogus Ozdemiroglu", "Donatas Motiejunas", "Donta Hall",
    "Dorian Grosber", "Dovydas Giedraitis", "Duane Washington",
    "Dustin Sleva", "Dwayne Bacon", "Dylan Osetkowski",
    "Dyshawn Pierre", "Dzanan Musa", "Ebuka Izundu",
    "Edgaras Ulanovas", "Edwin Jackson", "Eleftherios Mantzoukas",
    "Eli Ndiaye", "Elias Harris", "Elias Rapieque",
    "Elie Okobo", "Elijah Bryant", "Ercan Osmani",
    "Erkan Yilmaz", "Evan Fournier", "Fabien Causeur",
    "Facundo Campazzo", "Filip Petrusev", "Frank Jackson",
    "Frank Kaminsky", "Frank Ntilikina", "Freddie Gillespie",
    "Furkan Korkmaz", "Gabriel Deck", "Gabriele Procida",
    "George Papas", "Georgios Papagiannis", "Georgios Tanoulis",
    "Giampaolo Ricci", "Giannoulis Larentzakis", "Giordano Bortolani",
    "Glynn Watson", "Guerschon Yabusele", "Guy Palatin",
    "Hamidou Diallo", "Hugo Gonzalez", "Iffe Lundberg",
    "Ignas Brazdeikis", "Ike Iroegbu", "Ioannis Papapetrou",
    "Isaac Bonga", "Isaac Nogues", "Isaia Cordinier",
    "Isaiah Canaan", "Ish Wainright", "Isiaha Mike",
    "Ismael Bako", "Ismael Kamagate", "Ismaila Diagne",
    "Ivan Kharchenkov", "Izundu Ebuka", "Jabari Parker",
    "Jaime Pradilla", "Jake Cohen", "Jaleen Smith",
    "James Nnaji", "James Nunnally", "James Webb Iii",
    "Jan Vesely", "Jared Harper", "Jaron Blossomgame",
    "Jasiel Rivero", "Jaylen Hoard", "Jeffrey Dowtin Jr",
    "Jeremy Morgan", "Jerian Grant", "Jimmy Clark Iii",
    "Joel Bolomboy", "Joel Parra", "Joffrey Lauvergne",
    "Johannes Thiemann", "Johannes Voigtmann", "John Brown",
    "John Dibartolomeo", "John Egbunu", "Johnathan Motley",
    "Jonas Mattisseck", "Jordan Loyd", "Jordan Mickey",
    "Jordan Nwora", "Josep Puerto", "Josh Nebo",
    "Juan Nunez", "Juancho Hernangomez", "Juani Marcos",
    "Juhann Begarin", "Justin Anderson", "Justin Bean",
    "Justin Robinson", "Justinian Jessup", "Justus Hollatz",
    "Kai Jones", "Kamar Baldwin", "Kameron Taylor",
    "Karim Jallow", "Kassius Robertson", "Keenan Evans",
    "Kenan Kamenjas", "Kendrick Nunn", "Kevarrius Hayes",
    "Kevin Pangos", "Kevin Punter", "Khalifa Diop",
    "Khalifa Koumadje", "Khem Birch", "Klemen Prepelic",
    "Konstantinos Mitoglou", "Kosta Kondic", "Kostas Antetokounmpo",
    "Kostas Papanikolaou", "Kostas Sloukas", "Kresimir Nikic",
    "Kyle Guy", "Kyle Hines", "Laurynas Birutis",
    "Lazar Stojkovic", "Leandro Bolmaro", "Leon Kratzer",
    "Leopold Cavaliere", "Levi Randolph", "Lonnie Walker Iv",
    "Lorenzo Brown", "Louis Olinde", "Luca Vildoza",
    "Luka Mitrovic", "Luka Samanic", "Lukas Lekavicius",
    "Luke Sikma", "Maik Kotsar", "Malte Delow",
    "Mam Jaiteh", "Mantas Rubstavicius", "Maodo Lo",
    "Marcio Santos", "Marco Belinelli", "Mario Hezonja",
    "Mario Nakic", "Marius Grigonis", "Marko Guduric",
    "Marko Simonovic", "Markquis Nowell", "Markus Howard",
    "Martin Hermannsson", "Mateusz Ponitka", "Mathias Lessort",
    "Matt Thomas", "Matteo Spagnolo", "Matthew Costello",
    "Matthew Mitchell", "Matthew Morgan", "Matthew Strazel",
    "Mbaye Ndiaye", "Mckinley Wright Iv", "Melih Mahmutoglu",
    "Melih Tunca", "Melvin Ajinca", "Metecan Birsen",
    "Mfiondu Kabengele", "Michalis Lountzis", "Mikael Jantunen",
    "Mike Daum", "Mike James", "Mike Scott",
    "Mike Tobey", "Milos Teodosic", "Mitar Bosnjakovic",
    "Moses Wright", "Mouhamed Faye", "Mouhamet Diouf",
    "Myles Cale", "Nadir Hifi", "Nando De Colo",
    "Nathan Reuvers", "Nathan Sestina", "Naz Mitrou-Long",
    "Neal Sako", "Nelson Weidemann", "Nemanja Dangubic",
    "Nemanja Nedovic", "Neno Dimitrijevic", "Niccolo Mannion",
    "Nick Calathes", "Nick Weiler-Babb", "Nicola Akele",
    "Nicolas Laprovittola", "Nicolo Melli", "Niels Giffey",
    "Nigel Hayes-Davis", "Nigel Williams-Goss", "Niklas Wimberg",
    "Nikola Kalinic", "Nikola Milutinov", "Nikola Mirotic",
    "Nikolaos Rogkavopoulos", "O'Shae J Brissett", "Ognjen Dobric",
    "Ognjen Jaramaz", "Ognjen Kuzmic", "Ognjen Radosic",
    "Omari Moore", "Omer Yurtseven", "Omiros Netzipoglou",
    "Onuralp Bitim", "Oscar Da Silva", "Ousmane Diop",
    "Ousmane Ndiaye", "Panagiotis Kalaitzakis", "Paris Lee",
    "Pavel Savkov", "Perry Dozier Jr", "Petr Cornelie",
    "Quinn Ellis", "Rafa Villar", "Rafi Menco",
    "Rayjon Tucker", "Richaun Holmes", "Rodrigue Beaubois",
    "Rokas Giedraitis", "Rokas Jokubaitis", "Rolands Smits",
    "Roman Sorkin", "Rudy Fernandez", "Saben Lee",
    "Saliou Niang", "Sander Raieste", "Sasha Vezenkov",
    "Scottie Wilbekin", "Sebastian Herrera", "Sehmus Hazer",
    "Semi Ojeleye", "Serge Ibaka", "Sergio De Larrea",
    "Sergio Llull", "Sergio Rodriguez", "Sertac Sanli",
    "Shabazz Napier", "Shake Milton", "Shane Larkin",
    "Shaquielle Mckissic", "Shaquille Harrison", "Shavon Shields",
    "Stanley Johnson", "Stefan Joksimovic", "Stefan Jovic",
    "Stefan Lazarevic", "Stefan Miljenovic", "Stefano Tonut",
    "Sterling Brown", "Sylvain Francisco", "Tadas Sedekerskis",
    "Tai Odiase", "Talen Horton Tucker", "Tamir Blatt",
    "Tarik Biberovic", "Tarik Black", "Terry Tarpey",
    "Theo Maledon", "Thomas Walkup", "Tibor Pleiss",
    "Tim Schneider", "Timothe Luwawu-Cabarrot", "Tj Leaf",
    "Tj Shorts", "Tomas Dimsa", "Tomas Satoransky",
    "Tomer Ginat", "Tornike Shengelia", "Trent Forrest",
    "Trevion Williams", "Trey Lyles", "Tyler Dorsey",
    "Tyler Ennis", "Tyrique Jones", "Tyrone Wallace",
    "Tyson Carter", "Tyson Ward", "Uros Plavsic",
    "Uros Trifunovic", "Usman Garuba", "Vanja Marinkovic",
    "Vasilije Micic", "Vassilis Toliopoulos", "Victor Claver",
    "Vincent Poirier", "Vitto Brown", "Vladimir Lucic",
    "Vlatko Cancar", "Wade Baldwin Iv", "Walter Tavares",
    "Wenyen Gabriel", "Will Clyburn", "Will Mcdowell-White",
    "William Rayman", "Willy Hernangomez", "Xavier Rathan-Mayes",
    "Yaacov Noam", "Yago Dos Santos", "Yakuba Ouattara",
    "Yam Madar", "Yanni Wetzell", "Youssoupha Fall",
    "Zach Leday", "Zachary Seljaas", "Ziga Samar",
];
